export const queryKeys = {
	inventory: ["inventory"],
	productCatalog: ["productCatalog"],
	receptions: ["receptions"],
	recepcionDetail: ["recepcionDetail"],
	kits: ["kits"],
	cabinetWarehouse: ["cabinetWarehouse"],
	warehouses: ["warehouses"],
	users: ["users"],
	replenishmentOrders: ["replenishmentOrders"],
	replenishmentOrderDetail: ["replenishmentOrderDetail"],
	unfulfilledProducts: ["unfulfilledProducts"],
	stockLimits: ["stockLimits"],
	deletedAndEmptyProductStock: ["deletedAndEmptyProductStock"],
};
