/**
 * AppType compatibility shim for RPC clients
 * 
 * This provides a type-safe way to access your Hono server routes
 * without importing the full server implementation.
 * 
 * Generated by scripts/extract-app-type.ts
 * DO NOT EDIT MANUALLY - This file will be overwritten
 */

// Import necessary Hono types
import type { Context, Hono, Input } from 'hono';

// Define the core API response interface
interface ApiResponse<T = unknown> {
	success: boolean;
	data?: T;
	message?: string;
	meta?: unknown[];
}

// Define the route definitions that match your server
type Routes = {
	'/': {
		$get: () => Promise<Response>;
	};
	'/api/auth/products/all': {
		$get: () => Promise<Response>;
	};
	'/api/auth/product-stock/all': {
		$get: () => Promise<Response>;
	};
	'/api/auth/product-stock/with-employee': {
		$get: () => Promise<Response>;
	};
	'/api/auth/cabinet-warehouse/all': {
		$get: () => Promise<Response>;
	};
	'/api/auth/employee/all': {
		$get: (args: { query: { userId: string } }) => Promise<Response>;
	};
	'/api/auth/withdraw-orders/all': {
		$get: () => Promise<Response>;
	};
	'/api/auth/withdraw-orders/details': {
		$get: (args: { query: { dateWithdraw: string } }) => Promise<Response>;
	};
	'/api/auth/withdraw-orders/create': {
		$post: (args: { 
			json: {
				dateWithdraw: string;
				userId: string;
				numItems: number;
				isComplete?: boolean;
			}
		}) => Promise<Response>;
	};
	'/api/auth/withdraw-orders/update': {
		$post: (args: { 
			json: {
				withdrawOrderId: string;
				dateReturn: string;
				isComplete: boolean;
			}
		}) => Promise<Response>;
	};
	'/api/auth/withdraw-orders/details/create': {
		$post: (args: { 
			json: {
				productId: string;
				withdrawOrderId: string;
				dateWithdraw: string;
				userId: string;
			}
		}) => Promise<Response>;
	};
	'/api/auth/withdraw-orders/details/update': {
		$post: (args: { 
			json: {
				id: string;
				dateReturn: string;
			}
		}) => Promise<Response>;
	};
};

/**
 * The AppType that provides full RPC client compatibility
 * This matches the structure expected by Hono's RPC client
 */
export type AppType = Routes;
