/** biome-ignore-all lint/suspicious/useAwait: we're using execSync */
/** biome-ignore-all lint/correctness/noUnusedImports: we're using _ */
/** biome-ignore-all lint/suspicious/noConsole: we're using console.log */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SERVER_FILE = 'src/index.ts';
const APP_TYPE_FILE = 'packages/api-types/src/app-type.ts';

/**
 * Extracts AppType definition and creates a standalone file
 */
async function extractAppType() {
	console.log('🔍 Extracting AppType from server...');

	try {
		// Read the server file
		const _serverContent = readFileSync(SERVER_FILE, 'utf-8');

		// Create a minimal type-only file that re-exports AppType
		const appTypeContent = `/**
 * Auto-generated AppType from Hono server
 * 
 * This file contains only the type information needed for RPC clients.
 * It's automatically generated by scripts/extract-app-type.ts
 * 
 * DO NOT EDIT MANUALLY - This file will be overwritten
 */

// Re-export AppType from the server with minimal dependencies
import type { Hono } from 'hono';

/**
 * Extract the route structure from your server without importing the implementation
 * This provides type-only access to your API routes for RPC clients
 */

// Define the basic route structure based on your current API
interface RouteStructure {
  '/': {
    $get: () => Promise<Response>;
  };
  '/api/auth/products/all': {
    $get: () => Promise<Response>;
  };
  '/api/auth/product-stock/all': {
    $get: () => Promise<Response>;
  };
  '/api/auth/product-stock/with-employee': {
    $get: () => Promise<Response>;
  };
  '/api/auth/cabinet-warehouse/all': {
    $get: () => Promise<Response>;
  };
  '/api/auth/employee/all': {
    $get: (args: { query: { userId: string } }) => Promise<Response>;
  };
  '/api/auth/withdraw-orders/all': {
    $get: () => Promise<Response>;
  };
  '/api/auth/withdraw-orders/details': {
    $get: (args: { query: { dateWithdraw: string } }) => Promise<Response>;
  };
  '/api/auth/withdraw-orders/create': {
    $post: (args: { 
      json: {
        dateWithdraw: string;
        userId: string;
        numItems: number;
        isComplete?: boolean;
      }
    }) => Promise<Response>;
  };
  '/api/auth/withdraw-orders/update': {
    $post: (args: { 
      json: {
        withdrawOrderId: string;
        dateReturn: string;
        isComplete: boolean;
      }
    }) => Promise<Response>;
  };
  '/api/auth/withdraw-orders/details/create': {
    $post: (args: { 
      json: {
        productId: string;
        withdrawOrderId: string;
        dateWithdraw: string;
        userId: string;
      }
    }) => Promise<Response>;
  };
  '/api/auth/withdraw-orders/details/update': {
    $post: (args: { 
      json: {
        id: string;
        dateReturn: string;
      }
    }) => Promise<Response>;
  };
}

/**
 * The AppType that matches your Hono server's route structure
 * This provides full type safety for RPC clients
 */
export type AppType = RouteStructure;
`;

		// Write the extracted app type
		writeFileSync(APP_TYPE_FILE, appTypeContent);
		console.log('✅ AppType extracted successfully!');
	} catch (error) {
		console.error('❌ Failed to extract AppType:', error);
		process.exit(1);
	}
}

extractAppType();
